### ISSUE TITLE
Dscord can no longer build due to changes to Phobos template isSomeString

### ISSUE THREAD

**Issue by MetaLang** [MetaLang/dscord#1]
```
dscord\src\dscord\util\json.d(332,5): Error: cannot modify immutable expression result
dscord\src\dscord\util\json.d(295,7): Error: template instance `dscord.util.json.loadSingleField!(PermissionOverwrite, immutable(char))` error instantiating
dscord\src\dscord\util\json.d(246,9):        instantiated from here: loadSingleField!(PermissionOverwrite, PermissionOverwriteType)
dscord\src\dscord\types\base.d(183,29):        instantiated from here: deserializeFromJSON!(PermissionOverwrite)
```

This is caused by https://github.com/dlang/phobos/pull/5291. As I explained there:
> The breakage is here (https://github.com/MetaLang/dscord/blob/master/src/dscord/util/json.d#L194). PermissionOverwriteType is an enum with a base type of string. Due to this pull request, trying to deserialize a field of type PermissionOverwrite now bypasses the isSomeString case as it now doesn't pass the isSomeString!PermissionOverwriteType check. It falls through to the isArray case and tries to serialize each individual immutable(char), which falls through to the default case and results in the code trying to write to an immutable value.
